#!/bin/sh

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`
GREEN=$'\e[0;32m'
YELLOW=$'\e[0;33m'
RED=$'\e[0;31m'
NC=$'\e[0m'

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
    oIFS=$IFS
    IFS='
    '
    SFILES="$1"
    IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

echo "${YELLOW}Checking PHP Lint... $NC"
for FILE in $SFILES
do
    php -l -d display_errors=0 $PROJECT/$FILE
    if [ $? != 0 ]
    then
        echo "${RED}Fix PHP Lint error before commit! $NC"
        exit 1
    fi
    FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then
    echo "${YELLOW}Running Code Sniffer. Code standard PSR2... $NC"
    php artisan phpcs:check
    if [ $? != 0 ]
    then
        echo "${RED}Fix PHP Coding Standard error before commit! $NC"
        exit 1
    fi
fi

echo "${GREEN}PASS! $NC"
exit $?
